// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Q_PIpUegqaerQelAV1_jFKG2TK-5igo',
    appId: '1:427856191522:web:7a1a93e3fc1d925368aa7b',
    messagingSenderId: '427856191522',
    projectId: 'neg-auto',
    authDomain: 'neg-auto.firebaseapp.com',
    storageBucket: 'neg-auto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkuG5JDRlmRgMkpiga0VGd4feoqMGhsU4',
    appId: '1:427856191522:android:960119a08b9b177f68aa7b',
    messagingSenderId: '427856191522',
    projectId: 'neg-auto',
    storageBucket: 'neg-auto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNfKLKuVqiKtG2yLE2DRwMiSlcd8CHnN4',
    appId: '1:427856191522:ios:081908bbcb76fe4668aa7b',
    messagingSenderId: '427856191522',
    projectId: 'neg-auto',
    storageBucket: 'neg-auto.appspot.com',
    iosClientId: '427856191522-h101kb2c0sgnjtdipu43shgvcesen89l.apps.googleusercontent.com',
    iosBundleId: 'com.example.neg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNfKLKuVqiKtG2yLE2DRwMiSlcd8CHnN4',
    appId: '1:427856191522:ios:081908bbcb76fe4668aa7b',
    messagingSenderId: '427856191522',
    projectId: 'neg-auto',
    storageBucket: 'neg-auto.appspot.com',
    iosClientId: '427856191522-h101kb2c0sgnjtdipu43shgvcesen89l.apps.googleusercontent.com',
    iosBundleId: 'com.example.neg',
  );
}
